CC = gcc
CFLAGS = -Wall -Wextra -g

make: ex1 ex2 ex3 ex4

ex1: ex1.c
	${CC} ${CFLAGS} ex1.c -o ex1

ex2 : ex2.c
	${CC} ${CFLAGS} ex2.c -o ex2

ex3 : ex3.c
	${CC} ${CFLAGS} ex3.c -o ex3

ex4 : ex4.c
	${CC} ${CFLAGS} ex4.c -o ex4

clean:
	rm -f ex1 ex2 ex3 ex4